name: "PR check"
on:
  pull_request:
    branches: [ main ]
jobs:
  pr-template-verifier:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install npm
        uses: actions/setup-node@v3
